version: '3'
services:
  db:
    image: postgres:11
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresy
      POSTGRES_DB: test_db
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/checkme:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
    # binding.pryを使うために追記
    tty: true
    stdin_open: true
volumes:
  postgresql-data:
    driver: local
